export const STARTED_FETCHING_GENERAL_STATS = "STARTED_FETCHING_GENERAL_STATS";
export const FINISHED_FETCHING_GENERAL_STATS =
  "FINISHED_FETCHING_GENERAL_STATS";
export const STARTED_FETCHING_GRAPH_STATS = "STARTED_FETCHING_GRAPH_STATS";
export const FINISHED_FETCHING_GRAPH_STATS = "FINISHED_FETCHING_GRAPH_STATS"

export const RECEIVED_API_ERROR = "RECEIVED_API_ERROR";
