export const MAKE_FORM_VISIBLE = "MAKE_FORM_VISIBLE";
export const MAKE_FORM_INVISIBLE = "MAKE_FORM_INVISIBLE";

export const STARTED_ADDING_TRANSACTION = "STARTED_ADDING_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const FINISHED_ADDING_TRANSACTION = "FINISHED_ADDING_TRANSACTION";
