export const STARTED_FETCHING_TRANSACTIONS = "STARTED_FETCHING_FEED";
export const FINISHED_FETCHING_TRANSACTIONS = "FINISHED_FETCHING_TRANSACTIONS";

export const LIKED_TRANSACTION = "LIKED_TRANSACTION";
export const UNLIKED_TRANSACTION = "UNLIKED_TRANSACTION";

export const RECEIVED_API_ERROR = "RECEIVED_API_ERROR";
