export const STARTED_FETCHING_GOAL = "STARTED_FETCHING_GOALS";
export const FINISHED_FETCHING_GOAL_STATE =
  "FINISHED_FETCHING_CURRENT_GOAL_STATE";

export const RECEIVED_API_ERROR = "RECEIVED_API_ERROR";
