export const FINISHED_FETCHING_TEAMS = "FINISHED_FETCHING_TEAMS";
export const FINISHED_REPLYING_TO_INVITE = "FINISHED_REPLYING_TO_INVITE";
export const RECEIVED_API_ERROR = "RECEIVED_API_ERROR";
export const SELECTED_TEAM = "SELECTED_TEAM";
export const CHANGE_TEAM = "CHANGE_TEAM";