require 'yaml'

$metadata = YAML.load_file('fastlane/metadata.yml')
$metadata["copyright"] = $metadata["copyright"].gsub("&current_year", Time.now.year.to_s)

def get_languages
  result = []
  $metadata["languages"].each do |key, value|
    result.push(key)
  end
  result
end

def get_language_property_hash(property)
  languages = $metadata["languages"]
  result = {}
  languages.each do |key, value|
    next unless value.key?(property)

    result[key] = value[property]
  end
  result
end

app_identifier            $metadata["app_identifier"]
username                  $metadata["username"]
app_rating_config_path    $metadata["app_rating_config_path"]
app_icon                  $metadata["app_icon"]
apple_watch_app_icon      $metadata["apple_watch_app_icon"]
price_tier                $metadata["price_tier"]
copyright                 $metadata["copyright"]
primary_category          $metadata["primary_category"]
secondary_category        $metadata["secondary_category"]
automatic_release         $metadata["automatic_release"]

languages(get_languages)

name(get_language_property_hash("name"))

subtitle(get_language_property_hash("short_description"))

description(get_language_property_hash("description"))

keywords(get_language_property_hash("keywords"))

promotional_text(get_language_property_hash("promotional_text"))

support_url(get_language_property_hash("support_url"))

marketing_url(get_language_property_hash("marketing_url"))

privacy_url(get_language_property_hash("privacy_url"))

app_review_information({
  first_name: $metadata["app_review_information"]["first_name"],
  last_name: $metadata["app_review_information"]["last_name"],
  phone_number: $metadata["app_review_information"]["phone_number"],
  email_address: $metadata["app_review_information"]["email_address"],
  demo_user: $metadata["app_review_information"]["demo_user"],
  demo_password: $metadata["app_review_information"]["demo_password"],
  notes: $metadata["app_review_information"]["notes"]
})
