require 'pry'

lane :deploy do
  if @build_hockey
    deploy_android
    deploy_ios
  end
end


def sanitizeDeliverString (deliverString)
   return deliverString.gsub("^[\r\n]+|\.|[\r\n]+$", '').delete('\'').delete("\u0000").gsub(/\A[[:space:]]+|[[:space:]]+\z/, '')
end

def getSingleDeliverOption(option)
  option = (((sh ("cat fastlane/Deliverfile | grep #{option}")).chomp.sub! option, ''))
  return option.delete("\"").delete(" ")
end

def getDeliverOption (option, language)
    options = (sh ("cat fastlane/Deliverfile | grep -Ezo '#{option}\\(([^\)]+)\)'")).chomp.sub! "#{option}(", ''
    options = sanitizeDeliverString(options)
    found = options.split("\",")
    for lang in found do
      if lang.include? language
        lang = lang.sub! (language + " =>"), ''
        lang = sanitizeDeliverString(lang).chomp('"').reverse.chomp('"').reverse
        return lang
      end
    end
    return ""
end

lane :prepare_android_metadata do
  languages = sanitizeDeliverString((sh("cat fastlane/Deliverfile | grep -Ezo 'languages\(([^\)]+)\)'").chomp.sub! 'languages(', '')).split(',').map { |n| sanitizeDeliverString(n) }
  p getDeliverOption("name", "nl-NL")

  sh 'rm -Rf fastlane/metadata/'
  sh 'mkdir -p fastlane/metadata/android'
  sh 'rm -Rf fastlane/screenshots/*'
  sh 'mkdir -p fastlane/screenshots/android/'

  for lang in languages do
    sh ("mkdir -p fastlane/metadata/android/#{lang}/images")
    sh ("mkdir -p fastlane/metadata/android/#{lang}/images/phoneScreenshots")
    sh ("mkdir -p fastlane/metadata/android/#{lang}/images/sevenInchScreenshots")
    sh ("mkdir -p fastlane/metadata/android/#{lang}/images/tenInchScreenshots")
    sh ("mkdir -p fastlane/metadata/android/#{lang}/images/tvScreenshots")
    sh ("mkdir -p fastlane/metadata/android/#{lang}/images/wearScreenshots")
    sh ("touch fastlane/metadata/android/#{lang}/video.txt")
    sh ("echo '#{getDeliverOption("name", "nl-NL")}' > fastlane/metadata/android/#{lang}/title.txt")
    sh ("echo '#{getDeliverOption("short_description", "nl-NL")}' > fastlane/metadata/android/#{lang}/short_description.txt")
    sh ("echo '#{getDeliverOption("description", "nl-NL")}' > fastlane/metadata/android/#{lang}/full_description.txt")
    sh ("cp \"#{getSingleDeliverOption("app_icon")}\" fastlane/metadata/android/#{lang}/images/icon.png")
    sh ("cp \"#{getSingleDeliverOption("feature_graphic")}\" fastlane/metadata/android/#{lang}/images/featureGraphic.png")
    sh ("cp \"#{getSingleDeliverOption("promo_graphic")}\" fastlane/metadata/android/#{lang}/images/promoGraphic.png")
  end

end

lane :deploy_android do
  FileUtils.rm_rf('cordova/platforms/android/build/outputs/apk/.', secure: true)
  version_splitted = @app_version.split "."
  android_version = version_splitted[0] + "00" + version_splitted[1] + version_splitted[2]


  sh('APP_ENV=#{@environment} bin/maji build android')

  unless @branch == 'appstore'

    hockey public_identifier: ENV['FL_HOCKEY_PUBLIC_IDENTIFIER_ANDROID'],
           apk: "#{Dir.pwd}/cordova/platforms/android/build/outputs/apk/android-debug.apk",
           create_update: true,
           bundle_version: android_version,
           bundle_short_version: @branch,
           status: '2',
           notes: @release_notes
  else
    # release procedure for play store here
    sh('APP_ENV=#{@environment} bin/maji build android --release')

    sign_apk(
      keystore_path: "#{currentDir}/fastlane/vault/android.jks",
      alias: "android-release-signed",
      storepass: "dMOvHv7BPvBSDBswx0RT5H1M6wPCGblw",
      tsa: "http://timestamp.comodoca.com/rfc316",
      apk_path: File.expand_path("cordova/platforms/android/build/outputs/apk/android-release-unsigned.apk", File.dirname(__FILE__))
    )

    zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")

    sh("calabash-android resign #{File.expand_path("cordova/platforms/android/build/outputs/apk/android-release-unsigned.apk", File.dirname(__FILE__))}")

    prepare_android_metadata

    avds_path = "~/.fastlane/avds/"
    sh("mkdir -p #{avds_path}")
    sh("rm -Rf #{avds_path}/*")
    sh("cp fastlane/avds/* #{avds_path}")

    automated_test_emulator_run(
      ADB_restart: false,
      AVD_setup_path: "#{currentDir}/fastlane/AVD_setup.json",
      shell_task:"cd #{File.expand_path("fastlane/", File.dirname(__FILE__))} && SCREENSHOT_PATH=#{File.expand_path("fastlane/screenshots/android/", File.dirname(__FILE__))}/ bundler exec calabash-android run #{File.expand_path("cordova/platforms/android/build/outputs/apk/android-release-unsigned.apk", File.dirname(__FILE__))}"
    )

    # For now just copy it over to all the language directories. There's no way we can change the language of the phone from cli yet.
    sh 'echo $PWD && cp fastlane/screenshots/android/* fastlane/metadata/android/*/images/phoneScreenshots/'
    sh 'rm -Rf fastlane/screenshots/android/'


    supply  track: "production",
            apk: "#{currentDir}/cordova/platforms/android/build/outputs/apk/android-release.apk",
            json_key: "#{currentDir}/fastlane/vault/GOOGLE_JSON_KEY_FILE.json",
            package_name: @app_identifier,
            metadata_path: "#{currentDir}/fastlane/metadata/android/"
  end
end

lane :deploy_ios do
    FileUtils.rm_rf('cordova/platforms/ios/build/device/.', secure: true)

    #Make sure the old result is removed
    sh("rm -Rf tmp/output/#{@app_name}.result/")
    sh("rm -Rf tmp/output/#{@app_name}.result/")

    # where the signed ipa is placed
    output_dir = File.join(Dir.pwd, 'tmp/output')
    setup_jenkins(output_directory: output_dir)

    #Download the profile from apple so we can obtain the profile_uuid of the provisioning profile
    sh("rm -Rf profiles/")
    sh("mkdir profiles")
    sh("fastlane sigh --provisioning_name=\"match AdHoc #{@app_identifier}\" --username=\"info@kabisa.nl\" --app_identifier=\"#{@app_identifier}\" --skip_install --adhoc --ignore_profiles_with_different_name --output_path=\"./profiles\"")
    sh("security cms -D -i ./profiles/AdHoc_#{@app_identifier}.mobileprovision > ./profiles/AdHoc_#{@app_identifier}.plist || true")
    profile_uuid = sh("/usr/libexec/PlistBuddy -c \"Print :UUID\" ./profiles/AdHoc_#{@app_identifier}.plist").chomp
    sh("rm -R profiles/")

    #Build the app for ios
    sh("APP_ENV=#{@environment} bin/maji build ios -- --codeSignIdentity=\"iPhone Distribution: Kabisa BV (#{@team_id})\" --developmentTeam=\"#{@team_id}\" --packageType=\"adHoc\" --provisioningProfile=\"#{profile_uuid}\"")

    match username: 'info@kabisa.nl',
          git_url: 'git@github.com:kabisa/match-certificates.git',
          type: 'adhoc',
          app_identifier: @app_identifier,
          force_for_new_devices: :true

    #Make sure automatic code signing is disabled, we dont want this.
    disable_automatic_code_signing(
        path: "#{currentDir}/cordova/platforms/ios/#{@app_name}.xcodeproj",
        team_id: @team_id
    )

    #Make sure the correct provisioning profiles are setup based on the earlier obtained profile_uuid
    update_project_provisioning(
      xcodeproj: "#{currentDir}/cordova/platforms/ios/#{@app_name}.xcodeproj",
      profile: "/Users/jenkins/Library/MobileDevice/Provisioning\ Profiles/#{profile_uuid}.mobileprovision",
      build_configuration: "Release"
    )

    upgrade_super_old_xcode_project(
      path: "#{currentDir}/cordova/platforms/ios/#{@app_name}.xcodeproj",
      team_id: @team_id
    )

    # opening xcode prevents timeout
    sh("open -a xcode cordova/platforms/ios/#{@app_name}.xcodeproj")

    gym scheme: @app_name,
        project: "#{currentDir}/cordova/platforms/ios/#{@app_name}.xcodeproj",
        export_method: "ad-hoc"


    unless @branch == 'appstore'
      hockey public_identifier: ENV['FL_HOCKEY_PUBLIC_IDENTIFIER_IOS'],
             ipa: File.join(output_dir, "#{@app_name}.ipa"),
             create_update: true,
             bundle_version: @app_version,
             bundle_short_version: @branch,
             status: '2',
             notes: @release_notes

    else
      # release procedure for appstore here
      # Make sure old screenshots are removed
      sh 'rm -Rf fastlane/screenshots/*'

      #generate new screenshots
  	  snapshot  project: "#{currentDir}/cordova/platforms/ios/#{@app_name}.xcodeproj",
  	            output_directory: "#{currentDir}/fastlane/screenshots/",
  	            scheme: @app_name


      deliver ipa: "#{output_dir}/#{@app_name}.ipa",
              submit_for_review: true,
              force: true,
              username: "info@kabisa.nl",
              overwrite_screenshots: true,
              metadata_path: "#{currentDir}/fastlane/metadata/",
              screenshots_path: "#{currentDir}/fastlane/screenshots/",
              app_icon: "#{currentDir}/src/assets/logo/AppStore-1024.png"

    end

end

def currentDir
  File.basename(Dir.getwd)
end

def inFastlane
  currentDir == 'fastlane'
end

before_all do
  message =  changelog_from_git_commits(commits_count: 1)
  @app_version = sh('cat ../cordova/config.xml | grep \'^<widget\' | sed -E \'s|^.*version="([^"]+)".*|\1|\'').chomp
  @app_name = sh('cat ../cordova/config.xml | grep -E \'<name>(.*?)<\/name>\' | sed -e \'s,.*<name>\([^<]*\)</name>.*,\1,g\'').chomp
  @team_id = sh('cat ../cordova/config.xml | grep -E \'<team_id>(.*?)<\/team_id>\' | sed -e \'s,.*<team_id>\([^<]*\)</team_id>.*,\1,g\'').chomp
  @app_identifier = sh('cat ../cordova/package.json | grep -o \'"name": *"[^"]*"\'  | grep -o \'"[^"]*"$\'').chomp.gsub!(/\A"|"\Z/, '')
  @environment = "development"
  if @branch == 'appstore'
     @environment = "production"
  end
  @build_hockey = message.include?('BUILD_HOCKEY')
  @release_notes = message.gsub('BUILD_HOCKEY', '')
  @branch = git_branch.gsub('origin/', '')
  Dir.chdir('..') if inFastlane
end
