$LOAD_PATH << '.'
require './fastlane/helpers/metadata_helper.rb'
helper = Metadata_helper.new

clear_previous_screenshots true
stop_after_first_error true

ios_version '11.1'
app_identifier helper.get_property('app_identifier')

# A list of devices you want to take the screenshots from
 devices(helper.get_property('ios_devices'))

# Languages to create screenshots for
languages(helper.get_languages)



