
ios_version '11.1'

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 7 Plus",
   "iPad Pro (12.9-inch) (2nd generation)"
 ])

# Languages to create screenshots for
languages([
  "en-US",
  "nl-NL",
])
