export const LOGOUT_USER = "LOGOUT_USER";
export const STARTED_FETCHING_USERSTATS = "STARTED_FETCHING_USERSTATS";
export const FINISHED_FETCHING_USERSTATS = "FINISHED_FETCHING_USERSTATS";

export const RECEIVED_API_ERROR = "RECEIVED_API_ERROR";
