export const GOOGLE_TOKEN_SUCCESS = "GOOGLE_TOKEN_SUCCESS";
export const GOOGLE_TOKEN_FAILURE = "GOOGLE_TOKEN_FAILURE";

export const API_TOKEN_SUCCESS = "API_TOKEN_SUCCESS";
export const API_TOKEN_FAILURE = "API_TOKEN_FAILURE";

export const STARTED_STORING_FCM_TOKEN = "STORE_FCM_TOKEN";
export const STORED_FCM_TOKEN = "STORED_FCM_TOKEN";
