export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const ACCESS_TOKEN_FAILURE = "ACCESS_TOKEN_FAILURE";

export const STARTED_FETCHING_ACCESS_TOKEN = "STARTED_FETCHING_ACCESS_TOKEN";

export const LOGOUT_USER = "LOGOUT_USER";

export const INCORRECT_PARAMETERS = "INCORRECT_PARAMETERS";

export const STORED_FCM_TOKEN = "STORED_FCM_TOKEN";

export const ERROR_FCM_TOKEN = "ERROR_FCM_TOKEN";
